FROM node:20.12.1

ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
ENV CLERK_SECRET_KEY=
ENV NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
ENV NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
ENV CLERK_PUBLISHABLE_KEY=
ENV DATABASE_URL=
ENV NEXT_PUBLIC_APP_URL=

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
